easyjob:
    datasource:
       name: test
       url: jdbc:mysql://localhost:3306/easy_job?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
       username: root
       password: 123456
       driver-class-name: com.mysql.jdbc.Driver
    node:
      id: 2
    pool:
      queueSize: 1000
      coreSize: 5
      maxSize: 10
    heartBeat:
      enable: true
      seconds: 10
    recover:
      enable: true
      seconds: 30
